question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "Bananas are berries, but strawberries are not.", "answer": "True"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "The currency of Japan is the Yuan.", "answer": "False"},
    {"text": "Penguins are found in the Northern Hemisphere.", "answer": "False"},
    {"text": "The Eiffel Tower was originally intended for Barcelona.", "answer": "False"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The tallest mountain in the world is Mount Everest.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "The human skeleton is made up of 206 bones.", "answer": "True"},
    {"text": "Caffeine is a natural insecticide.", "answer": "True"},
]